//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9174
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrologParsec.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrologParsec.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _7_about {
            get {
                object obj = ResourceManager.GetObject("_7_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _8_about {
            get {
                object obj = ResourceManager.GetObject("_8_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add2000 {
            get {
                object obj = ResourceManager.GetObject("add2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addB {
            get {
                object obj = ResourceManager.GetObject("addB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AeroIcons {
            get {
                object obj = ResourceManager.GetObject("AeroIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November 28th, 2023.
        /// </summary>
        internal static string AppDate {
            get {
                return ResourceManager.GetString("AppDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A modern and light Prolog/Lisp editor.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built using Visual Studio 2005 and C#. Credits to Pavel Torgashov for &quot;Fast Colored Textbox&quot; and &quot;Autocomplete Menu&quot;. Prolog is a logic-based programming language. Built by fraaa3.
        /// </summary>
        internal static string AppDescription2 {
            get {
                return ResourceManager.GetString("AppDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testfire.
        /// </summary>
        internal static string AppEdition {
            get {
                return ResourceManager.GetString("AppEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logix.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.2.256.0.tf/p-231128.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap auroraStatic {
            get {
                object obj = ResourceManager.GetObject("auroraStatic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bacjB {
            get {
                object obj = ResourceManager.GetObject("bacjB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back2000 {
            get {
                object obj = ResourceManager.GetObject("back2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark {
            get {
                object obj = ResourceManager.GetObject("bookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark2000 {
            get {
                object obj = ResourceManager.GetObject("bookmark2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmarkB {
            get {
                object obj = ResourceManager.GetObject("bookmarkB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Class {
            get {
                object obj = ResourceManager.GetObject("Class", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap classicIcons {
            get {
                object obj = ResourceManager.GetObject("classicIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy1 {
            get {
                object obj = ResourceManager.GetObject("Copy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy2000 {
            get {
                object obj = ResourceManager.GetObject("copy2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copyB {
            get {
                object obj = ResourceManager.GetObject("copyB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copyEW {
            get {
                object obj = ResourceManager.GetObject("copyEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cut1 {
            get {
                object obj = ResourceManager.GetObject("Cut1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut2000 {
            get {
                object obj = ResourceManager.GetObject("cut2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cutB {
            get {
                object obj = ResourceManager.GetObject("cutB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cutEW {
            get {
                object obj = ResourceManager.GetObject("cutEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dark {
            get {
                object obj = ResourceManager.GetObject("dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete2000 {
            get {
                object obj = ResourceManager.GetObject("delete2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deleteB {
            get {
                object obj = ResourceManager.GetObject("deleteB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon emacs {
            get {
                object obj = ResourceManager.GetObject("emacs", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emacsIcon {
            get {
                object obj = ResourceManager.GetObject("emacsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Event {
            get {
                object obj = ResourceManager.GetObject("Event", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find2000 {
            get {
                object obj = ResourceManager.GetObject("find2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap findB {
            get {
                object obj = ResourceManager.GetObject("findB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap findEW {
            get {
                object obj = ResourceManager.GetObject("findEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flatMetro {
            get {
                object obj = ResourceManager.GetObject("flatMetro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fluentIcons {
            get {
                object obj = ResourceManager.GetObject("fluentIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font {
            get {
                object obj = ResourceManager.GetObject("Font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Font2000 {
            get {
                object obj = ResourceManager.GetObject("Font2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fontB {
            get {
                object obj = ResourceManager.GetObject("fontB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap go_to {
            get {
                object obj = ResourceManager.GetObject("go_to", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap go_to2000 {
            get {
                object obj = ResourceManager.GetObject("go_to2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap go_toB {
            get {
                object obj = ResourceManager.GetObject("go_toB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gramlex {
            get {
                object obj = ResourceManager.GetObject("gramlex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gramlex2000 {
            get {
                object obj = ResourceManager.GetObject("gramlex2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gramlexAero {
            get {
                object obj = ResourceManager.GetObject("gramlexAero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gramlexB {
            get {
                object obj = ResourceManager.GetObject("gramlexB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Immagine1 {
            get {
                object obj = ResourceManager.GetObject("Immagine1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lc_list_add {
            get {
                object obj = ResourceManager.GetObject("lc_list_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lc_open {
            get {
                object obj = ResourceManager.GetObject("lc_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lc_zoomtoolbox {
            get {
                object obj = ResourceManager.GetObject("lc_zoomtoolbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap light {
            get {
                object obj = ResourceManager.GetObject("light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap link2000 {
            get {
                object obj = ResourceManager.GetObject("link2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap linkB {
            get {
                object obj = ResourceManager.GetObject("linkB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaAdd {
            get {
                object obj = ResourceManager.GetObject("lunaAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaBack {
            get {
                object obj = ResourceManager.GetObject("lunaBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaBookMark {
            get {
                object obj = ResourceManager.GetObject("lunaBookMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaCopy {
            get {
                object obj = ResourceManager.GetObject("lunaCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaCut {
            get {
                object obj = ResourceManager.GetObject("lunaCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaDelete1 {
            get {
                object obj = ResourceManager.GetObject("lunaDelete1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaFind {
            get {
                object obj = ResourceManager.GetObject("lunaFind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaFont {
            get {
                object obj = ResourceManager.GetObject("lunaFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaGoTo {
            get {
                object obj = ResourceManager.GetObject("lunaGoTo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaGramlex {
            get {
                object obj = ResourceManager.GetObject("lunaGramlex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaIcons {
            get {
                object obj = ResourceManager.GetObject("lunaIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaLink {
            get {
                object obj = ResourceManager.GetObject("lunaLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaNew {
            get {
                object obj = ResourceManager.GetObject("lunaNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaNext {
            get {
                object obj = ResourceManager.GetObject("lunaNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaOpen {
            get {
                object obj = ResourceManager.GetObject("lunaOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaPaste {
            get {
                object obj = ResourceManager.GetObject("lunaPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaRedo {
            get {
                object obj = ResourceManager.GetObject("lunaRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaRemove {
            get {
                object obj = ResourceManager.GetObject("lunaRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaSave {
            get {
                object obj = ResourceManager.GetObject("lunaSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaSelect {
            get {
                object obj = ResourceManager.GetObject("lunaSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lunaUndo {
            get {
                object obj = ResourceManager.GetObject("lunaUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macAdd {
            get {
                object obj = ResourceManager.GetObject("macAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macBack {
            get {
                object obj = ResourceManager.GetObject("macBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macBookmark {
            get {
                object obj = ResourceManager.GetObject("macBookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macCopy {
            get {
                object obj = ResourceManager.GetObject("macCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macCut {
            get {
                object obj = ResourceManager.GetObject("macCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macDelete {
            get {
                object obj = ResourceManager.GetObject("macDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macFind {
            get {
                object obj = ResourceManager.GetObject("macFind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macFont {
            get {
                object obj = ResourceManager.GetObject("macFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macForward {
            get {
                object obj = ResourceManager.GetObject("macForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macGo_to {
            get {
                object obj = ResourceManager.GetObject("macGo_to", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macGramlex {
            get {
                object obj = ResourceManager.GetObject("macGramlex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macLink {
            get {
                object obj = ResourceManager.GetObject("macLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macNew {
            get {
                object obj = ResourceManager.GetObject("macNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macOpen {
            get {
                object obj = ResourceManager.GetObject("macOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macPaste {
            get {
                object obj = ResourceManager.GetObject("macPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macRedo {
            get {
                object obj = ResourceManager.GetObject("macRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macRemove {
            get {
                object obj = ResourceManager.GetObject("macRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macRename {
            get {
                object obj = ResourceManager.GetObject("macRename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macSave {
            get {
                object obj = ResourceManager.GetObject("macSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macSelect {
            get {
                object obj = ResourceManager.GetObject("macSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macUndo {
            get {
                object obj = ResourceManager.GetObject("macUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ME_about {
            get {
                object obj = ResourceManager.GetObject("ME_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Method {
            get {
                object obj = ResourceManager.GetObject("Method", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new2000 {
            get {
                object obj = ResourceManager.GetObject("new2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newB {
            get {
                object obj = ResourceManager.GetObject("newB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newEW {
            get {
                object obj = ResourceManager.GetObject("newEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next2000 {
            get {
                object obj = ResourceManager.GetObject("next2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nextB {
            get {
                object obj = ResourceManager.GetObject("nextB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open2000 {
            get {
                object obj = ResourceManager.GetObject("open2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open200032 {
            get {
                object obj = ResourceManager.GetObject("open200032", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Open32 {
            get {
                object obj = ResourceManager.GetObject("Open32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openB {
            get {
                object obj = ResourceManager.GetObject("openB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openEW {
            get {
                object obj = ResourceManager.GetObject("openEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OS9 {
            get {
                object obj = ResourceManager.GetObject("OS9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherBookmark {
            get {
                object obj = ResourceManager.GetObject("pantherBookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherCopy {
            get {
                object obj = ResourceManager.GetObject("pantherCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherCut {
            get {
                object obj = ResourceManager.GetObject("pantherCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherFind {
            get {
                object obj = ResourceManager.GetObject("pantherFind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherFont {
            get {
                object obj = ResourceManager.GetObject("pantherFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherGoTo {
            get {
                object obj = ResourceManager.GetObject("pantherGoTo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherIcon {
            get {
                object obj = ResourceManager.GetObject("pantherIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherLink {
            get {
                object obj = ResourceManager.GetObject("pantherLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherMenu {
            get {
                object obj = ResourceManager.GetObject("pantherMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherNew {
            get {
                object obj = ResourceManager.GetObject("pantherNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherNew16 {
            get {
                object obj = ResourceManager.GetObject("pantherNew16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherOpen {
            get {
                object obj = ResourceManager.GetObject("pantherOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherOpen16 {
            get {
                object obj = ResourceManager.GetObject("pantherOpen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherPaste {
            get {
                object obj = ResourceManager.GetObject("pantherPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherRedo {
            get {
                object obj = ResourceManager.GetObject("pantherRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherSave {
            get {
                object obj = ResourceManager.GetObject("pantherSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherSelect {
            get {
                object obj = ResourceManager.GetObject("pantherSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pantherUndo {
            get {
                object obj = ResourceManager.GetObject("pantherUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paste1 {
            get {
                object obj = ResourceManager.GetObject("Paste1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste2000 {
            get {
                object obj = ResourceManager.GetObject("paste2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pasteB {
            get {
                object obj = ResourceManager.GetObject("pasteB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pasteEW {
            get {
                object obj = ResourceManager.GetObject("pasteEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An easy-to-use GUI for JFlex and ByaccJ.
        /// </summary>
        internal static string PEDescription {
            get {
                return ResourceManager.GetString("PEDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built using Visual Studio 2005 and C#. JFlex is a program built by the JFlex team on jflex.de. ByaccJ is a program built by Tomas Hurka on byaccj.sourceforge.net.  Built by fraaa3.
        /// </summary>
        internal static string PEDescription2 {
            get {
                return ResourceManager.GetString("PEDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperdemo (Logix).
        /// </summary>
        internal static string PEEdition {
            get {
                return ResourceManager.GetString("PEEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gramlex.
        /// </summary>
        internal static string PEName {
            get {
                return ResourceManager.GetString("PEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5.543.0.lx/p-231128.
        /// </summary>
        internal static string PEVersion {
            get {
                return ResourceManager.GetString("PEVersion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap plebeo {
            get {
                object obj = ResourceManager.GetObject("plebeo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon prolog {
            get {
                object obj = ResourceManager.GetObject("prolog", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Property {
            get {
                object obj = ResourceManager.GetObject("Property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Redo1 {
            get {
                object obj = ResourceManager.GetObject("Redo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redo2000 {
            get {
                object obj = ResourceManager.GetObject("redo2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redoB {
            get {
                object obj = ResourceManager.GetObject("redoB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remove2000 {
            get {
                object obj = ResourceManager.GetObject("remove2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removeB {
            get {
                object obj = ResourceManager.GetObject("removeB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rename2000 {
            get {
                object obj = ResourceManager.GetObject("rename2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap renameB {
            get {
                object obj = ResourceManager.GetObject("renameB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save2000 {
            get {
                object obj = ResourceManager.GetObject("save2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save2EW {
            get {
                object obj = ResourceManager.GetObject("save2EW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveB {
            get {
                object obj = ResourceManager.GetObject("saveB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveEW {
            get {
                object obj = ResourceManager.GetObject("saveEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_closedoc {
            get {
                object obj = ResourceManager.GetObject("sc_closedoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_copy {
            get {
                object obj = ResourceManager.GetObject("sc_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_cut {
            get {
                object obj = ResourceManager.GetObject("sc_cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_delete {
            get {
                object obj = ResourceManager.GetObject("sc_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_fontdialog {
            get {
                object obj = ResourceManager.GetObject("sc_fontdialog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_gotoendofdoc {
            get {
                object obj = ResourceManager.GetObject("sc_gotoendofdoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_gotopage {
            get {
                object obj = ResourceManager.GetObject("sc_gotopage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_gotostartoftable {
            get {
                object obj = ResourceManager.GetObject("sc_gotostartoftable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_gramlex {
            get {
                object obj = ResourceManager.GetObject("sc_gramlex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_newdoc {
            get {
                object obj = ResourceManager.GetObject("sc_newdoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_open {
            get {
                object obj = ResourceManager.GetObject("sc_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_paste {
            get {
                object obj = ResourceManager.GetObject("sc_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_redo {
            get {
                object obj = ResourceManager.GetObject("sc_redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_rename {
            get {
                object obj = ResourceManager.GetObject("sc_rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_save {
            get {
                object obj = ResourceManager.GetObject("sc_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_selectall {
            get {
                object obj = ResourceManager.GetObject("sc_selectall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_star {
            get {
                object obj = ResourceManager.GetObject("sc_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_undo {
            get {
                object obj = ResourceManager.GetObject("sc_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc_webhtml {
            get {
                object obj = ResourceManager.GetObject("sc_webhtml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select {
            get {
                object obj = ResourceManager.GetObject("select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select2000 {
            get {
                object obj = ResourceManager.GetObject("select2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap selectB {
            get {
                object obj = ResourceManager.GetObject("selectB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Swipl.
        /// </summary>
        internal static string SwiHomeDirectory {
            get {
                return ResourceManager.GetString("SwiHomeDirectory", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap system {
            get {
                object obj = ResourceManager.GetObject("system", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tab_Sheet_New {
            get {
                object obj = ResourceManager.GetObject("Tab_Sheet_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab2000 {
            get {
                object obj = ResourceManager.GetObject("tab2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tabB {
            get {
                object obj = ResourceManager.GetObject("tabB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Undo1 {
            get {
                object obj = ResourceManager.GetObject("Undo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo2000 {
            get {
                object obj = ResourceManager.GetObject("undo2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undoB {
            get {
                object obj = ResourceManager.GetObject("undoB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undoEW {
            get {
                object obj = ResourceManager.GetObject("undoEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_about {
            get {
                object obj = ResourceManager.GetObject("vista_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap word {
            get {
                object obj = ResourceManager.GetObject("word", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon xml_file_icon_8 {
            get {
                object obj = ResourceManager.GetObject("xml_file_icon_8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap XP_about {
            get {
                object obj = ResourceManager.GetObject("XP_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
