//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9174
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrologParsec.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("prolog.xml")]
        public string descriptionFileDirectory {
            get {
                return ((string)(this["descriptionFileDirectory"]));
            }
            set {
                this["descriptionFileDirectory"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string defaultFontSize {
            get {
                return ((string)(this["defaultFontSize"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProggyCleanTT, 15.75pt")]
        public global::System.Drawing.Font defaultFont {
            get {
                return ((global::System.Drawing.Font)(this["defaultFont"]));
            }
            set {
                this["defaultFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("% -*- Mode: Prolog -*-")]
        public string headerText {
            get {
                return ((string)(this["headerText"]));
            }
            set {
                this["headerText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("% -*- End of file -- ")]
        public string footerText {
            get {
                return ((string)(this["footerText"]));
            }
            set {
                this["footerText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool documentMap {
            get {
                return ((bool)(this["documentMap"]));
            }
            set {
                this["documentMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aurora.svg")]
        public string auroraFile {
            get {
                return ((string)(this["auroraFile"]));
            }
            set {
                this["auroraFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Asain\\Documents\\linguaggi\\prolog\\PrologParsec - Copia\\PrologParsec\\bin\\D" +
            "ebug\\xml.xml")]
        public string xmlFile {
            get {
                return ((string)(this["xmlFile"]));
            }
            set {
                this["xmlFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool auroraStartPage {
            get {
                return ((bool)(this["auroraStartPage"]));
            }
            set {
                this["auroraStartPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("system")]
        public string appTheme {
            get {
                return ((string)(this["appTheme"]));
            }
            set {
                this["appTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int leftPaddingToolbar {
            get {
                return ((int)(this["leftPaddingToolbar"]));
            }
            set {
                this["leftPaddingToolbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int rightPaddingToolbar {
            get {
                return ((int)(this["rightPaddingToolbar"]));
            }
            set {
                this["rightPaddingToolbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool auroraCustom {
            get {
                return ((bool)(this["auroraCustom"]));
            }
            set {
                this["auroraCustom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string auroraCustomURL {
            get {
                return ((string)(this["auroraCustomURL"]));
            }
            set {
                this["auroraCustomURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startPageVisible {
            get {
                return ((bool)(this["startPageVisible"]));
            }
            set {
                this["startPageVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startPageQuick {
            get {
                return ((bool)(this["startPageQuick"]));
            }
            set {
                this["startPageQuick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startPageChangelog {
            get {
                return ((bool)(this["startPageChangelog"]));
            }
            set {
                this["startPageChangelog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startPageLogo {
            get {
                return ((bool)(this["startPageLogo"]));
            }
            set {
                this["startPageLogo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startPageVersion {
            get {
                return ((bool)(this["startPageVersion"]));
            }
            set {
                this["startPageVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startPageProduct {
            get {
                return ((bool)(this["startPageProduct"]));
            }
            set {
                this["startPageProduct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startPageEdition {
            get {
                return ((bool)(this["startPageEdition"]));
            }
            set {
                this["startPageEdition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startPageDesc {
            get {
                return ((bool)(this["startPageDesc"]));
            }
            set {
                this["startPageDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startPageStartup {
            get {
                return ((bool)(this["startPageStartup"]));
            }
            set {
                this["startPageStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool untitledFileStartup {
            get {
                return ((bool)(this["untitledFileStartup"]));
            }
            set {
                this["untitledFileStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bold")]
        public global::System.Drawing.FontStyle keywordFontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["keywordFontStyle"]));
            }
            set {
                this["keywordFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bold")]
        public global::System.Drawing.FontStyle commaFontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["commaFontStyle"]));
            }
            set {
                this["commaFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bold")]
        public global::System.Drawing.FontStyle pointFontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["pointFontStyle"]));
            }
            set {
                this["pointFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle questionFontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["questionFontStyle"]));
            }
            set {
                this["questionFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle systemParFontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["systemParFontStyle"]));
            }
            set {
                this["systemParFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle equalsFontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["equalsFontStyle"]));
            }
            set {
                this["equalsFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle anonFontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["anonFontStyle"]));
            }
            set {
                this["anonFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Italic")]
        public global::System.Drawing.FontStyle commentFontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["commentFontStyle"]));
            }
            set {
                this["commentFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bold")]
        public global::System.Drawing.FontStyle parentesiFontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["parentesiFontStyle"]));
            }
            set {
                this["parentesiFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::System.Drawing.Color keywordForeColor {
            get {
                return ((global::System.Drawing.Color)(this["keywordForeColor"]));
            }
            set {
                this["keywordForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color keywordBackColor {
            get {
                return ((global::System.Drawing.Color)(this["keywordBackColor"]));
            }
            set {
                this["keywordBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color commaForeColor {
            get {
                return ((global::System.Drawing.Color)(this["commaForeColor"]));
            }
            set {
                this["commaForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color commaBackColor {
            get {
                return ((global::System.Drawing.Color)(this["commaBackColor"]));
            }
            set {
                this["commaBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Goldenrod")]
        public global::System.Drawing.Color pointForeColor {
            get {
                return ((global::System.Drawing.Color)(this["pointForeColor"]));
            }
            set {
                this["pointForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color pointBackColor {
            get {
                return ((global::System.Drawing.Color)(this["pointBackColor"]));
            }
            set {
                this["pointBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color questionForeColor {
            get {
                return ((global::System.Drawing.Color)(this["questionForeColor"]));
            }
            set {
                this["questionForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color questionBackColor {
            get {
                return ((global::System.Drawing.Color)(this["questionBackColor"]));
            }
            set {
                this["questionBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Coral")]
        public global::System.Drawing.Color systemParForeColor {
            get {
                return ((global::System.Drawing.Color)(this["systemParForeColor"]));
            }
            set {
                this["systemParForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color systemParBackColor {
            get {
                return ((global::System.Drawing.Color)(this["systemParBackColor"]));
            }
            set {
                this["systemParBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteelBlue")]
        public global::System.Drawing.Color equalsForeColor {
            get {
                return ((global::System.Drawing.Color)(this["equalsForeColor"]));
            }
            set {
                this["equalsForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color equalsBackColor {
            get {
                return ((global::System.Drawing.Color)(this["equalsBackColor"]));
            }
            set {
                this["equalsBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrchid")]
        public global::System.Drawing.Color anonForeColor {
            get {
                return ((global::System.Drawing.Color)(this["anonForeColor"]));
            }
            set {
                this["anonForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color anonBackColor {
            get {
                return ((global::System.Drawing.Color)(this["anonBackColor"]));
            }
            set {
                this["anonBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color commentForeColor {
            get {
                return ((global::System.Drawing.Color)(this["commentForeColor"]));
            }
            set {
                this["commentForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color commentBackColor {
            get {
                return ((global::System.Drawing.Color)(this["commentBackColor"]));
            }
            set {
                this["commentBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color parentesiForeColor {
            get {
                return ((global::System.Drawing.Color)(this["parentesiForeColor"]));
            }
            set {
                this["parentesiForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color parentesiBackColor {
            get {
                return ((global::System.Drawing.Color)(this["parentesiBackColor"]));
            }
            set {
                this["parentesiBackColor"] = value;
            }
        }
    }
}
